### ISSUE TITLE
nethunter kex passwd /usr/bin/kex: line 25: vncpasswd: command not found

### ISSUE THREAD

**Issue by hrjisan** [RaynerSec/Kali-Nethunter-In-Termux#1]
Help I can't set kex passwd

**Comment by rc-chuah** [comment]
First Type This Command In Termux: nethunter
Then Type This Command In Nethunter: sudo apt-get update && sudo apt-get install tightvncserver
Then Exit Nethunter To Termux Type This Command: nethunter kex passwd
