### ISSUE TITLE
Error:404 Not Found

### ISSUE THREAD

**Issue by Vall1331** [RaynerSec/Kali-Nethunter-In-Termux#2]
![Screenshot_20241208-103521](https://github.com/user-attachments/assets/d15a9368-9596-42f8-9cd4-981edd66a4af)
How do I solve the 404 not found error? And this error (as I think) appears at the end of the installation. What is the reason for this error?

**Comment by rc-chuah** [comment]
> ![Screenshot_20241208-103521](https://github.com/user-attachments/assets/d15a9368-9596-42f8-9cd4-981edd66a4af)
> How do I solve the 404 not found error? And this error (as I think) appears at the end of the installation. What is the reason for this error?

I Will Fix This Error Soon; The Error Is Due to Kali Linux FS Filename Has Changed.

**Comment by Vall1331** [comment]
Okay, thanks!
